import 'dart:io';

import '../config/models/project_config.dart';
import '../discovery/project_discovery.dart';
import '../graph/project_graph.dart';
import '../graph/schema.dart';
import '../inference/architecture_inference.dart';
import '../inference/canonical_reference.dart';
import '../inference/feature_clustering.dart';
import '../inference/naming_inference.dart';
import '../inference/state_management_detector.dart';
import '../scanner/detectors/route_detector.dart';
import '../shared/paths.dart';
import 'agents_md_generator.dart';
import 'architecture_md_generator.dart';
import 'cursor_rule_generator.dart';
import 'project_md_generator.dart';
import 'routes_md_generator.dart';

/// Orchestrates all context file generation.
class ContextGenerator {
  ContextGenerator({
    ProjectMdGenerator? projectMd,
    ArchitectureMdGenerator? architectureMd,
    AgentsMdGenerator? agentsMd,
    CursorRuleGenerator? cursorRule,
    RoutesMdGenerator? routesMd,
  })  : _projectMd = projectMd ?? ProjectMdGenerator(),
        _architectureMd = architectureMd ?? ArchitectureMdGenerator(),
        _agentsMd = agentsMd ?? AgentsMdGenerator(),
        _cursorRule = cursorRule ?? CursorRuleGenerator(),
        _routesMd = routesMd ?? RoutesMdGenerator();

  final ProjectMdGenerator _projectMd;
  final ArchitectureMdGenerator _architectureMd;
  final AgentsMdGenerator _agentsMd;
  final CursorRuleGenerator _cursorRule;
  final RoutesMdGenerator _routesMd;

  void generateAll({
    required ProjectPaths paths,
    required ProjectConfig config,
    required DiscoveryResult discovery,
    required ProjectGraph graph,
    required StateManagementResult stateManagement,
    required ArchitectureInference architecture,
    required List<FeatureCluster> features,
    required CanonicalReference? canonical,
    String? interpretation,
    List<DetectedRoute> routes = const [],
  }) {
    final naming = NamingInference().infer(graph);

    _write(
        paths.aiFile('project.md'),
        _projectMd.generate(
          discovery: discovery,
          stateManagement: stateManagement,
          architecture: architecture,
          features: features,
        ));

    _write(
        paths.aiFile('architecture.md'),
        _architectureMd.generate(
          stateManagement: stateManagement,
          architecture: architecture,
          declaredStateManagement:
              config.stateManagement != 'auto' ? config.stateManagement : null,
        ));

    _write(paths.aiFile('dependencies.md'), _generateDependencies(discovery));
    _write(paths.aiFile('conventions.md'), _generateConventions(naming));
    _write(paths.aiFile('features.md'), _generateFeatures(features));
    _write(paths.aiFile('services.md'), _generateServices(graph));
    _write(paths.aiFile('models.md'), _generateModels(graph));
    _write(paths.aiFile('routes.md'), _routesMd.generate(routes));

    if (config.generateAgentsMd) {
      _write(
        paths.agentsMd,
        _agentsMd.generate(
          projectName: discovery.projectName,
          stateManagement: stateManagement,
          architecture: architecture,
          canonical: canonical,
          declaredStateManagement:
              config.stateManagement != 'auto' ? config.stateManagement : null,
          interpretation: interpretation,
        ),
      );
    }

    if (config.generateCursorRule) {
      _write(
        paths.cursorRuleFile,
        _cursorRule.generate(
          projectName: discovery.projectName,
          primaryStateManagement: config.stateManagement != 'auto'
              ? config.stateManagement
              : stateManagement.primary,
        ),
      );
    }
  }

  void _write(String path, String content) {
    File(path).parent.createSync(recursive: true);
    File(path).writeAsStringSync(content);
  }

  String _generateDependencies(DiscoveryResult discovery) {
    final buffer = StringBuffer();
    buffer.writeln('# Dependencies\n');
    buffer.writeln('<!-- AUTO-GENERATED BY flutter_ai_context. -->\n');
    for (final dep in discovery.dependencies) {
      buffer.writeln('- **${dep.name}** (${dep.category.name})');
    }
    return buffer.toString();
  }

  String _generateConventions(List<NamingConvention> naming) {
    final buffer = StringBuffer();
    buffer.writeln('# Naming Conventions\n');
    buffer.writeln('<!-- AUTO-GENERATED BY flutter_ai_context. -->\n');
    for (final conv in naming) {
      buffer.writeln(
        '- **${conv.role}**: `${conv.preferredPattern}` (${(conv.confidence * 100).toStringAsFixed(0)}% confidence)',
      );
    }
    return buffer.toString();
  }

  String _generateFeatures(List<FeatureCluster> features) {
    final buffer = StringBuffer();
    buffer.writeln('# Features\n');
    buffer.writeln('<!-- AUTO-GENERATED BY flutter_ai_context. -->\n');
    for (final feature in features) {
      buffer.writeln('## ${feature.name}');
      for (final member in feature.members) {
        buffer.writeln('- `$member`');
      }
      buffer.writeln();
    }
    return buffer.toString();
  }

  String _generateServices(ProjectGraph graph) {
    final buffer = StringBuffer();
    buffer.writeln('# Services\n');
    buffer.writeln('<!-- AUTO-GENERATED BY flutter_ai_context. -->\n');
    for (final node in graph.nodes) {
      if (node.type == NodeType.service || node.type == NodeType.apiClient) {
        buffer.writeln('- **${node.name}** — `${node.file ?? 'unknown'}`');
      }
    }
    return buffer.toString();
  }

  String _generateModels(ProjectGraph graph) {
    final buffer = StringBuffer();
    buffer.writeln('# Models\n');
    buffer.writeln('<!-- AUTO-GENERATED BY flutter_ai_context. -->\n');
    for (final node in graph.nodes) {
      if (node.type == NodeType.model) {
        buffer.writeln('- **${node.name}** — `${node.file ?? 'unknown'}`');
      }
    }
    return buffer.toString();
  }
}
