/// Standard auto-generated header for output files.
class MarkdownHeader {
  static const notice = '''
<!-- AUTO-GENERATED BY flutter_ai_context. -->
<!-- Do not edit manually. -->
<!-- Run `flutter_ai_context sync` to regenerate. -->
''';

  static String title(String name) => '# $name\n\n$notice\n';
}
